#! /bin/sh

### BEGIN INIT INFO
# Provides:          pwrmgt
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting power off daemon"
    /opt/pwrmgt/pwroffd.py &
    /opt/pwrmgt/fanmgtd.py &
    ;;
  stop)
    echo "Stopping power off daemon"
    pkill -f /opt/pwrmgt/fanmgtd.py
    pkill -f /opt/pwrmgt/pwroffd.py
    ;;
  *)
    echo "Usage: /etc/init.d/pwrmgt {start|stop}"
    exit 1
    ;;
esac

exit 0

